# Generated by Django 5.0.6 on 2024-05-11 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(choices=[('1st Floor', '1st Floor'), ('2nd Floor', '2nd Floor'), ('3rd Floor', '3rd Floor'), ('1st Floor Closet', '1st Floor Closet'), ('Closet 1', 'Closet 1'), ('Closet 2', 'Closet 2'), ('Closet 3', 'Closet 3'), ('Closet 4', 'Closet 4')], max_length=20, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_address', models.CharField(max_length=40, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('picture', models.ImageField(default='avatar.jpeg', upload_to='Pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
