# Generated by Django 5.0.6 on 2024-05-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventoryNum',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
